apiVersion: v1
kind: Pod
metadata:
  name: inventory
  namespace: inventory-space
  labels:
    app.kubernetes.io/name: inventory
spec:
  containers:
    - name: mqtt
      image: 094412661274.dkr.ecr.ap-southeast-2.amazonaws.com/milestone-3_mqtt:arm64
      ports:
        - containerPort: 1883
        - containerPort: 9001
    - name: graphdb
      image: neo4j:latest
      env:
       - name: NEO4J_AUTH
         value: neo4j/8bitguy123
      ports:
        - containerPort: 7474
        - containerPort: 7687
    - name: backend
      image: 094412661274.dkr.ecr.ap-southeast-2.amazonaws.com/milestone-3_backend:arm64
      ports:
        - containerPort: 8080
    - name: frontend
      image: 094412661274.dkr.ecr.ap-southeast-2.amazonaws.com/milestone-3_frontend:arm64
      env:
       - name: MQTT_HOST
         value: localhost
       - name: REST_HOST
         value: localhost
      ports:
        - containerPort: 8081
          name: web-svc
