apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend
        image: mgrcse/milestone-3_frontend:arm64
        env:
        - name: MQTT_HOST
          value: localhost
        - name: REST_HOST
          value: localhost
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: node-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: node-frontend
