apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app.kubernetes.io/name: inventory
    
  ports:
  - name: http-service
    protocol: TCP
    port: 8081
    targetPort: web-svc
