apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-backend
  template:
    metadata:
      labels:
        app: spring-boot-backend
    spec:
      containers:
      - name: spring-boot-backend
        image: mgrcse/milestone-3_backend:amd64
        env:
        - name: MQTT_HOST
          value: localhost
        ports:
        - containerPort: 8080
          name: apiport
      - name: graphdb
        image: neo4j:latest
        env:
        - name: NEO4J_AUTH
          value: neo4j/8bitguy123
      - name: mqtt
        image: mgrcse/milestone-3_mqtt:amd64
        ports:
        - containerPort: 1883
          name: mqtttcp
        - containerPort: 9002
          name: mqttws
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: aptport
  - port: 9002
    name: mqttws
  selector:
    app: spring-boot-backend
