version: '2'

services:
  mqtt:
    container_name: mqtt
    image: mgrcse/milestone-3_mqtt:arm64
    ports:
     - "9002:9002"

  graphdb:
    container_name: graphdb
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/8bitguy123

  backend:
    container_name: spring-boot-backend
    image: mgrcse/milestone-3_backend:arm64
    environment:
      - DB_URL=bolt://graphdb:7687
      - MQTT_HOST=mqtt
    ports:
     - "8080:8080"
    depends_on:
      - mqtt
      - graphdb

  frontend:
    container_name: node-frontend
    image: mgrcse/milestone-3_frontend:arm64
    environment:
      - REST_HOST=localhost
      - MQTT_HOST=localhost
    ports:
     - "8081:8081"
    depends_on:
     - backend
    